version: 0.2
phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip"
      - "unzip terraform_1.1.9_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan

  post-build:
    commands:
      - echo- terraform $TF_COMMAND completed omn 'date'