version: 0.2
phases:
  install:
    commands:
      - "docker pull hashicorp/terraform:latest"
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan

